### ISSUE TITLE
Bug report: Case studies menu

### ISSUE THREAD

**Issue by smborio** [maths/stack-web#23]
If you open the Case Studies dropdown and hover over the year then it gives you the different case studies for that year. However, if you click on a year, then it is impossible to get back to that year's case studies unless you refresh the website.

**Comment by sangwinc** [comment]
@smborio I think this issue is now resolved by @samfearn's recent changes.  Can you confirm and close it?

**Comment by smborio** [comment]
@sangwinc it looks like the website was re-build after merging @samfearn's PR and the bug is still there.

**Comment by samfearn** [comment]
Yes I didn't try to address this in the recent PR. I'll try to look into it, but not sure what's causing this at this point, so no promises.

**Comment by samfearn** [comment]
Started looking into this briefly.

The bootstrap mkdocs theme uses .dropdown-menu and .dropdown-submenu classes in the navbar (among others). When one hovers over a .dropdown-submenu class (for example, the 2023 nav item within the Case Studies top level nav item), any direct descendent .dropdown-menu gets the css display:block, overriding the default display:none. So the menu showing the actual 2023 case studies gets display:block once I hover over the 2023 section in the nav, making it visible.

However, if one clicks on the 2023 section, the child menu (of 2023 case studies) suddenly gains class .show, as well as some additional positioning styles, the latter of which leaves the menu offscreen, even when it should become visible on hover.

I haven't yet been able to find out what adds the new class and style commands. Presumably a js onClick somewhere?

**Comment by samfearn** [comment]
Ah! It's the function showInnerDropdown(item) on line 97 of base.js from the main mkdocs theme.

**Comment by samfearn** [comment]
This PR has been merged. Do you want to check this fixes the bug and then close this @smborio?

**Comment by smborio** [comment]
Thanks @samfearn for sorting this out. The new behaviour is not standard - when you click, hovering stops working and you then need to click on another year to open the options. I think it's a great improvement as you can go back to any year after clicking so I'm happy to close it and will let others re-open it if they disagree with me.

**Comment by samfearn** [comment]
Yes this was a deliberate decision: clicking toggles the submenu on, which can be helpful if for any reason a user struggles to reliably move their cursor from hovering over the section (I.e “2023”) into the submenu to click an item. I’m sure we’ve all experienced UIs where by the time you move your cursor to the submenu, then submenu has disappeared because the UI no longer considers you to be hovering over the thing which generates the submenu.

Once you have a toggle-on submenu, you then need to pause the hovering on the others, otherwise you’ll have multiple submenus stacking one on top of another. Not only is this ugly, but for anyone who wants this as an accessibility feature, they don’t want the other submenus anyway. As you noticed, I set it up so that one can toggle the submenu back off in order to restore the hover behaviour, and also one can directly toggle another submenu on instead.

I realised after I made the PR that the visual state of the section (eg 2023) once you’ve activated the toggle on, should probably be distinct from the hover state; at the moment they gain the same slight grey background in both cases. At some point I’ll make the toggle-on state slightly darker.
